### ISSUE TITLE
Types aren't being built in the specified place.

### ISSUE THREAD

**Issue by jnguyenmt** [zeusdeux/use-is-in-viewport#11]
You aren't specifying the declaration directory in tsconfig but you are specifying a place in package.json ("types": "built/src/index.d.ts").

So currently, if I install your package with yarn and try to use it, typescript will gripe about no typings. Adjusting in either place should fix it. Not sure where you'd want to do it so it's up to you or I can put in a PR!

![image](https://user-images.githubusercontent.com/48927312/78606242-fd309300-782a-11ea-8404-a582647f2321.png)

**Comment by zeusdeux** [comment]
Thanks for the PR! Landed in [`v1.0.9`](https://github.com/zeusdeux/use-is-in-viewport/releases/tag/v1.0.9) ^_^
