### ISSUE TITLE
How to observe only when element is in view, and not when it goes out of view?

### ISSUE THREAD

**Issue by bitttttten** [zeusdeux/use-is-in-viewport#6]
I would like just to track when the element comes into view, and keep the boolean `true` for the rest of the session duration. At the moment the library toggles back and forth. Is it possible to do it?

I dug into your options and the options in `observe-element-in-viewport` and I couldn't find anything 👀

**Comment by zeusdeux** [comment]
You can do this via observe-element-in-viewport by using the [`await isInViewport(target)` format](https://github.com/zeusdeux/observe-element-in-viewport#one-time-query-to-check-if-target-element-is-in-viewport) for a one off all.

This hook doesn't support it natively but you can build a custom hook based on this hook to do so as shown below —

```js
import { useState } from 'react'
import useIsInViewport from 'use-is-in-viewport'

function useIsInViewportOnce(options) {
  const [isInViewport, ...etc] = useIsInViewport(options)
  const [t, setT] = useState(isInViewport)
  
  setT(previousT => {
    if (previousT) {
      setT(previousT)
    } else {
      setT(isInViewport)
    }
  })

  return [t, ...etc]
}
```

**Comment by zeusdeux** [comment]
Did this solution work for you @bitttttten? If so, I'd love to close this issue. If not, I am down to discuss and solve it differently.

**Comment by bitttttten** [comment]
Ah sorry, I did something very similar. Something like this:

```ts
import { useEffect, useState } from 'react'
import useIsInViewport, { CallbackRef, HookOptions } from 'use-is-in-viewport'

export const useHasBeenInViewportOnce = (
    options?: HookOptions,
): [boolean, CallbackRef, CallbackRef] => {
    const [isInViewport, ref, viewportRef] = useIsInViewport(options)
    const [hasBeenInViewportOnce, setHasBeen] = useState(false)

    useEffect(() => {
        if (isInViewport && !hasBeenInViewportOnce) {
            setHasBeen(true)
        }
    }, [isInViewport, options, hasBeenInViewportOnce])

    return [hasBeenInViewportOnce, ref, viewportRef]
}
```

**Comment by bitttttten** [comment]
The only other improvement would be to add this natively or include it in the library:

`import useIsInViewportOnce from 'use-is-in-viewport/once'

And if you don't want to do to that, then no worries and there's nothing more to discuss we can close the issue.

**Comment by zeusdeux** [comment]
Glad your use case was tackled! We can revisit exposing it from this package itself once more requests for it show up!

**Comment by zeusdeux** [comment]
I have gone ahead and added it [as an example in the readme](https://github.com/zeusdeux/use-is-in-viewport/blob/master/Readme.md#example-6-composing-with-usestate-to-create-a-custom-hook-that-clamps-to-true-once-the-target-element-is-in-viewport) as a first step.

**Comment by fcabanasm** [comment]
> You can (somewhat) approximate this via by using the [`await isInViewport(target)` format](https://github.com/zeusdeux/observe-element-in-viewport#one-time-query-to-check-if-target-element-is-in-viewport). I wouldn't recommend it though has that would meet your usecase only if the element was already outside the viewport to begin with.
> 
> Instead, while this hook doesn't support it natively, you can build a custom hook based on this hook to do so as shown below —
> 
> ```js
> import { useState } from 'react'
> import useIsInViewport from 'use-is-in-viewport'
> 
> function useClampedIsInViewport(options) {
>   const [isInViewport, ...etc] = useIsInViewport(options)
>   const [wasInViewportAtleastOnce, setWasInViewportAtleastOnce] = useState(isInViewport)
>   
>   setWasInViewportAtleastOnce(prev => {
>     // this will clamp it to the first true
>     // received from useIsInViewport
>     if (!prev) {
>       return isInViewport
>     }
>     return prev
>   })
> 
>   return [wasInViewportAtleastOnce, ...etc]
> }
> ```

its actually does not working :(

**Comment by zeusdeux** [comment]
@fcabanasm Ah yeah I was missing a `useEffect` in there. Here's a working one.

```ts
function useClampedIsInViewport(
  options?: HookOptions
): ReturnType<typeof useIsInViewport> {
  const [isInViewport, ...etc] = useIsInViewport(options)
  const [
    wasInViewportAtleastOnce,
    setWasInViewportAtleastOnce
  ] = React.useState(isInViewport)

  React.useEffect(() => {
    setWasInViewportAtleastOnce((prev) => {
      // this will clamp it to the first true
      // received from useIsInViewport
      if (!prev) {
        return isInViewport
      }
      return prev
    })
  }, [isInViewport])

  return [wasInViewportAtleastOnce, ...etc]
}
```
