### ISSUE TITLE
Track visibility of conditionally-rendered component

### ISSUE THREAD

**Issue by nwalters512** [zeusdeux/use-is-in-viewport#7]
We're composing this hook as part of our analytics framework and ran into an interesting case where the component we're trying to monitor the visibility of is conditionally rendered based on the loading state of some data. Specifically, the component that the `ref` returned by this hook gets attached to isn't mounted after the first render. This causes problems with this hook, as it assumes that the `ref` will have been attached to a DOM node after the first render: https://github.com/zeusdeux/use-is-in-viewport/blob/ec47313df2529a6f273e0813b202a7af1b400cee/src/index.ts#L48-58.

I believe this could be fixed by modifying the `useEffect()` call in this hook to the following:

```diff
  useEffect(() => {
+   if (childRef.current) {
      return observeElementInViewport(
        childRef.current,
        () => setIsInViewport(true),
        () => setIsInViewport(false),
        {
          ...restOpts,
          viewport: parentRef.current
        }
      )
+   }
- }, [childRef, restOpts, parentRef])
+ }, [childRef.current, restOpts, parentRef])
```

I'd be happy to put up a PR for this, but wanted to get feedback from a maintainer before doing so. Let me know if you see any problems with this approach!

Thanks for building this awesome hook 🙏

**Comment by zeusdeux** [comment]
Ah nice catch! Shows how I assumed certain things without realizing 'em! Your change should also handle the parent itself not being rendered (which would mean none of its children are).
I'd love a PR. Would you mind adding test cases as well please? One for the conditional rendering of the child and one for the parent itself.

Thanks for the report @nwalters512!

**Comment by nwalters512** [comment]
Sure thing! I'll work on a PR for that now.

**Comment by nwalters512** [comment]
@zeusdeux question about the parent test you're asking for - are you talking specifically about the viewport? E.g., don't render the viewport (and thus not the child either), and make sure things work as expected?

**Comment by zeusdeux** [comment]
@nwalters512 Yupp, exactly that!
